name: Test
jobs:
  asdf:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'asdf' }}
    steps:
    - run: echo "This is an asdf dispatch"
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    needs: asdf
    defaults:
      run:
        shell: bash
    steps:
    - name: Set branch output variable
      run: echo "${GITHUB_REF#refs/heads/}"
    - name: Dump
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: echo secret
      run: echo ${{ toJson(secrets.test) }}
    - name: Printf test
      run: echo '${{ github.event.client_payload.example }}' | xargs printf '%s\n'
    - name: Printf test2
      run: echo "$MY_VAL" | xargs printf '%s\n'
      env:
        MY_VAL: ${{ github.event.client_payload.example }}
    - name: Printf test2
      run: echo "hello \"world today\"" | xargs printf '%s\n'
    - name: basename test
      run: basename a/b/c
    - name: dirname test
      run: basename $(dirname a/b/c)
on:
  push:
    branches:
    - '**'
    tags-ignore:
    - v*
