on: [push,pull_request,repository_dispatch]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        MY_VAL: ${{ github.event.client_payload.example }}
      run: echo "$GITHUB_CONTEXT"
    - name: echo secret
      run: echo ${{ toJson(secrets.test) }}
    - name: Printf test
      run: echo "${{ github.event.client_payload.example }}" | xargs printf '%s\n'
    - name: Printf test2
      run: echo "$MY_VAL" | xargs printf '%s\n'
    - name: Printf test2
      run: echo "hello \"world today\"" | xargs printf '%s\n'


