on: [push,pull_request,repository_dispatch]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: echo secret
      run: echo ${{ secrets.test }}

